{
 "title": "Mikrotik Interfaces",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interface",
    "query": {
     "query": "label_values(mikrotik_interface_last_update,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RX/TX speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(mikrotik_interface_rx_bytes{name=\"${interface}\"}[$__rate_interval])*8) by (name)",
     "legendFormat": "{{name}} rx"
    },
    {
     "expr": "sum(rate(mikrotik_interface_tx_bytes{name=\"${interface}\"}[$__rate_interval])*8) by (name)",
     "legendFormat": "{{name}} tx"
    }
   ]
  },
  { "title": "Transfer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Transfer used [1h]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mikrotik_interface_tx_bytes{name=\"${interface}\"}[1h]) + increase(mikrotik_interface_rx_bytes{name=\"${interface}\"}[1h])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer used [24h]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mikrotik_interface_tx_bytes{name=\"${interface}\"}[24h]) + increase(mikrotik_interface_rx_bytes{name=\"${interface}\"}[24h])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer used [7d]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mikrotik_interface_tx_bytes{name=\"${interface}\"}[7d]) + increase(mikrotik_interface_rx_bytes{name=\"${interface}\"}[7d])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer used [30d]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mikrotik_interface_tx_bytes{name=\"${interface}\"}[30d]) + increase(mikrotik_interface_rx_bytes{name=\"${interface}\"}[30d])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer used every hour up to specified hour (last 24h)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(mikrotik_interface_tx_bytes{name=\"${interface}\"}[1h]) + increase(mikrotik_interface_rx_bytes{name=\"${interface}\"}[1h])) by (name)",
     "legendFormat": "hourly usage"
    }
   ]
  },
  {
   "title": "Transfer used every day up to specified day (last 31 days)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(mikrotik_interface_tx_bytes{name=\"${interface}\"}[1d]) + increase(mikrotik_interface_rx_bytes{name=\"${interface}\"}[1d])) by (name)",
     "legendFormat": "daily usage"
    }
   ]
  },
  {
   "title": "Transfer used every month up to specified month (month = 30 days)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(mikrotik_interface_tx_bytes{name=\"${interface}\"}[30d]) + increase(mikrotik_interface_rx_bytes{name=\"${interface}\"}[30d])) by (name)",
     "legendFormat": "monthly usage (30 days)"
    }
   ]
  }
 ]
}